### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by clem** [Egregors/pySplash#3]
Hi there :wave:

I'm searching for an Unsplash Wallaper Mac application I can contribute to and I tried PySplash a few minutes ago.
Unfortunately, I only got this "Connection Error" message:

![connection-error](https://user-images.githubusercontent.com/100307/128012478-53f22146-c333-4938-9f3a-ec082311b86d.png)

I don't know why as long as Unsplash is not down, and my internet connection works!

Thanks a lot for this app and keep building great stuff!

**Comment by egregors** [comment]
Sup @clem! Thanks for your feedback! I didn't touch this project for a long time but looks like that is the time. I'll check this error out in few days and will try to fix it. 

I bet, Unsplash did change their API and it will be easy to fix. But I wanna upgrade App to a modern stack (py3, deps) as well. I hope, it will not raise problems.

**Comment by clem** [comment]
Hey @egregors. Thanks for your quick reply. 

Sounds great! I can be a beta-tester if you need one.

**Comment by egregors** [comment]
@clem So, let's see. This project is really old, so I just wrote the new one: https://github.com/egregors/splsh

For now, it's very raw a has a lot of problems, but it works! 
One of the problems – auto-build artifacts for a macOS, so you have to build App from the source (you need Go version 1.16).

To building it by yourself just run `make release` and if all going well in `dist` folder you will get your Splsh app.

I'd like to make it in a proper way, but it requires some time. So, I looking forward to your feedback

![image](https://user-images.githubusercontent.com/2153895/128602649-81a565b8-ce3e-4985-8ec9-839ae64e058b.png)

**Comment by clem** [comment]
@egregors Thanks for your reactivity. I close this issue and create another in the new repository with my feedbacks 👌 

PS : I will create some issues in this new repository. Feel free to tell me if you need more information about them.
